import sqlite3

dbname = "./tweet_bot.db"
conn = sqlite3.connect(dbname)

cur = conn.cursor()

sqls = {
    "episodes": [
        "insert into Episodes (title) values ('はじまりのトキメキ');",
        "insert into Episodes (title) values ('Cutest♡ガール');",
        "insert into Episodes (title) values ('大好きを叫ぶ');",
        "insert into Episodes (title) values ('未知なるミチ');",
        "insert into Episodes (title) values ('今しかできないことを');",
        "insert into Episodes (title) values ('笑顔のカタチ（⸝⸝>▿<⸝⸝）');",
        "insert into Episodes (title) values ('ハルカカナタ');",
        "insert into Episodes (title) values ('しずく、モノクローム');",
        "insert into Episodes (title) values ('仲間でライバル');",
        "insert into Episodes (title) values ('夏、はじまる。');",
        "insert into Episodes (title) values ('みんなの夢、私の夢');",
        "insert into Episodes (title) values ('花ひらく想い');",
        "insert into Episodes (title) values ('みんなの夢を叶える場所（スクールアイドルフェスティバル）');",
    ],
    "characters": [
        "insert into Characters (name) values ('高咲侑');",
        "insert into Characters (name) values ('上原歩夢');",
        "insert into Characters (name) values ('中須かすみ');",
        "insert into Characters (name) values ('桜坂しずく');",
        "insert into Characters (name) values ('朝香果林');",
        "insert into Characters (name) values ('宮下愛');",
        "insert into Characters (name) values ('近江彼方');",
        "insert into Characters (name) values ('優木せつ菜');",
        "insert into Characters (name) values ('エマ・ヴェルデ');",
        "insert into Characters (name) values ('天王寺璃奈');",
        "insert into Characters (name) values ('三船栞子');",
        "insert into Characters (name) values ('ミア・テイラー');",
        "insert into Characters (name) values ('鐘嵐珠');",
        "insert into Characters (name) values ('中川菜々');",
        "insert into Characters (name) values ('黒しずく');",
        "insert into Characters (name) values ('演劇部部長');",
        "insert into Characters (name) values ('はんぺん');",
        "insert into Characters (name) values ('色葉');",
        "insert into Characters (name) values ('今日子');",
        "insert into Characters (name) values ('浅希');",
        "insert into Characters (name) values ('近江遥');",
        "insert into Characters (name) values ('クリスティーナ');",
        "insert into Characters (name) values ('支倉かさね');",
        "insert into Characters (name) values ('綾小路姫乃');",
        "insert into Characters (name) values ('紫藤美咲');",
        "insert into Characters (name) values ('生徒会副会長');",
        "insert into Characters (name) values ('生徒会書記');",
        "insert into Characters (name) values ('女子高生A&B');",
        "insert into Characters (name) values ('流しそうめん同好会部員');",
    ],
    "quotes": [
        "insert into Quotes (episode, character, quote) values (1, 1, '生まれたトキメキ\nあの日から世界は　変わり始めたんだ');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'いまいち　トキメキが足りないねえ');",
        "insert into Quotes (episode, character, quote) values (1, 1, '歩夢　これいいんじゃない？\n似合うと思うよ');",
        "insert into Quotes (episode, character, quote) values (1, 1, '着たい服着ればいいじゃん　歩夢は何着たってかわいいよ');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'い…　いいよ！　かわいいとは思うけど子供っぽいって〜');",
        "insert into Quotes (episode, character, quote) values (1, 2, '小学生の時の話でしょ？　もうそういうのは卒業だよ');",
        "insert into Quotes (episode, character, quote) values (1, 1, '着たい服着ればいいじゃん　歩夢は何着たってかわいいよ');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'もう　またそんな適当なことを…');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'あっ　見て見て\n幼稚園の時　こんなカッコしてたよね');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'あ〜　懐かしいねえ');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'あゆぴょんだぴょん！');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'かわいかったなあ…\nねえ\nちょっとやってみてよ\nあゆぴょん');",
        "insert into Quotes (episode, character, quote) values (1, 2, '…は？');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'やるわけないでしょ　もう');",
        "insert into Quotes (episode, character, quote) values (1, 1, '賛成だぴょ〜ん');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'ゆうぴょんの方がかわいいんじゃない？');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'それはないぴょ〜ん');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'やっぱり　コッペパンじゃない？');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'ねえねえ　今日の2限でさあ〜…');",
        "insert into Quotes (episode, character, quote) values (1, 2, '食べる？　限定のレモン塩カスタード');",
        "insert into Quotes (episode, character, quote) values (1, 1, '何かピンとくるのないんだよね〜\nまあ　いつもどおり適当に…');",
        "insert into Quotes (episode, character, quote) values (1, 28, 'あれ？　せつ菜ちゃん一人？\n新しいグループのお披露目だったよね');",
        "insert into Quotes (episode, character, quote) values (1, 1, '結構盛り上がってるね　行ってみよっか');",
        "insert into Quotes (episode, character, quote) values (1, 8, 'ハァ…　ハァ…');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'かっこよかった！　かわいかった！　ヤバいよ　あんな子いるんだね！\n何だろう　この気持ち！　すっごいトキメキ！');",
        "insert into Quotes (episode, character, quote) values (1, 1, '虹ヶ咲って…\nうちの高校だ〜！');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'うちの高校だ〜！');",
        "insert into Quotes (episode, character, quote) values (1, 2, '寝不足？');",
        "insert into Quotes (episode, character, quote) values (1, 2, '遅刻しないでよ？');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'その前に　ちょっと寄りたいとこあるんだけど　いい？');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'あっ…　うわっ！\nえ？　ちょ…　ちょっと〜！');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'あっ…\nあの　侑ちゃん！\n私　まだ…');",
        "insert into Quotes (episode, character, quote) values (1, 1, '私　スクールアイドルって　よく知らなかったからさ\n昨日帰ってから　動画とかいっぱい見たんだよね\nみんなかっこよくて…　かわいくて…　輝いていて…！\nもう…　完全にトキめいちゃった！');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'でも　やっぱり一番は昨日のあの人！\n優木せつ菜ちゃんっていうんだって！');",
        "insert into Quotes (episode, character, quote) values (1, 2, '「ちゃん」！？');",
        "insert into Quotes (episode, character, quote) values (1, 1, '結構有名みたいなんだよね　神出鬼没のニジガク謎のスクールアイドルって！\nファンクラブとかあるのかなあ　次のライブ　決まってるなら行きたいなあ');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'で…　でも　私たちもう2年だし　二人で予備校通うって言ってたよね？\nスクールアイドルなんて追っかけてる暇ないんじゃ…');",
        "insert into Quotes (episode, character, quote) values (1, 1, '問題なし！　むしろプラス！\nせつ菜ちゃんの歌聴きながら勉強したら　すっごくはかどったし\n今日の小テストもバッチリだった！');",
        "insert into Quotes (episode, character, quote) values (1, 1, '何かさ　すっごくやる気が湧いてくるんだよね\nこんな気持ちになったの初めて！');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'まずはサインをもらわなきゃ！　歩夢　いくよ！');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'おお！　ここが部室棟か〜');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'ねえ　スクールアイドル同好会の部室って…　どこ？');",
        "insert into Quotes (episode, character, quote) values (1, 1, '片っ端から聞いて回ればいいんじゃない？');",
        "insert into Quotes (episode, character, quote) values (1, 29, '流しそうめん同好会にようこそ！　入部希望ですか？');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'いや　スクールアイドル同好会を探していて…');",
        "insert into Quotes (episode, character, quote) values (1, 29, '知らないなあ');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'おいしそう…');",
        "insert into Quotes (episode, character, quote) values (1, 1, '全然見つからな〜い…');",
        "insert into Quotes (episode, character, quote) values (1, 2, '部活も生徒数も多いからねえ…\n同好会だけで100個以上あるらしいよ');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'マジか…');",
        "insert into Quotes (episode, character, quote) values (1, 10, 'あ…');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'あ〜…\nもしかして　急ぎとかだったかな…');",
        "insert into Quotes (episode, character, quote) values (1, 6, 'どしたん？　りなりー ');",
        "insert into Quotes (episode, character, quote) values (1, 10, 'あ　愛さん');",
        "insert into Quotes (episode, character, quote) values (1, 6, 'ほら　スクールアイドル同好会はここだよ');",
        "insert into Quotes (episode, character, quote) values (1, 1, '誰に聞いても分からなかったのに…');",
        "insert into Quotes (episode, character, quote) values (1, 6, '確か　今年出来たばっかの同好会だしね');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'ありがとう！　助かったよ');",
        "insert into Quotes (episode, character, quote) values (1, 6, 'どういたしまして');",
        "insert into Quotes (episode, character, quote) values (1, 10, '別に…　急いでなかった\n少しびっくりしただけ');",
        "insert into Quotes (episode, character, quote) values (1, 10, '好きなの？　スクールアイドル');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'え？　うん！\nはまったばっかだけどね〜');",
        "insert into Quotes (episode, character, quote) values (1, 10, 'そう…');",
        "insert into Quotes (episode, character, quote) values (1, 2, '…え？\nう…　うん　どうだろ？\nまだよく分からないかな');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'ここが…\n虹ヶ咲学園スクールアイドル同好会！');",
        "insert into Quotes (episode, character, quote) values (1, 14, '何をしているんですか？\n普通科2年　高咲侑さん　上原歩夢さん');",
        "insert into Quotes (episode, character, quote) values (1, 1, '会ったこと…　ありましたっけ？');",
        "insert into Quotes (episode, character, quote) values (1, 14, '生徒会長たるもの　当然　全生徒の名前を覚えているものです');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'へ？　生徒会長！？');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'へ？　生徒会長！？');",
        "insert into Quotes (episode, character, quote) values (1, 14, 'フッ…　中川菜々と申します');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'そういえば　生徒集会で見た覚えがあるような…');",
        "insert into Quotes (episode, character, quote) values (1, 14, 'この同好会にご用ですか？');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'はい！　優木せつ菜ちゃんに会いに来たんです！');",
        "insert into Quotes (episode, character, quote) values (1, 14, '彼女はもう　ここには来ませんよ\nスクールアイドルはやめたそうです');",
        "insert into Quotes (episode, character, quote) values (1, 4, '彼女だけではありません\nこのスクールアイドル同好会は…\nただいまをもって　廃部となりました');",
        "insert into Quotes (episode, character, quote) values (1, 4, '明日もまた　同じ日が来るのだろう\n幸福は一生来ないのだ　けれども…');",
        "insert into Quotes (episode, character, quote) values (1, 16, 'はい　そこまで\nじゃあ最後にグラウンド10周！');",
        "insert into Quotes (episode, character, quote) values (1, 16, '文句言わずにさっさと行く！');",
        "insert into Quotes (episode, character, quote) values (1, 16, 'しずく　聞いたよ　同好会の件\n掛け持ちじゃなくなったわけだし　これからは演劇部に専念できるんでしょ？');",
        "insert into Quotes (episode, character, quote) values (1, 7, 'すや〜　すや〜…\nハッ！　まずい　もう夕方じゃん\n急がなきゃ　またせつ菜ちゃんに…\nああ…　もう怒られないんだっけ…');",
        "insert into Quotes (episode, character, quote) values (1, 9, 'ハァ…');",
        "insert into Quotes (episode, character, quote) values (1, 5, '元気ないわね　エマ');",
        "insert into Quotes (episode, character, quote) values (1, 9, '果林ちゃん…　モデルのお仕事は？');",
        "insert into Quotes (episode, character, quote) values (1, 5, '今日は休み');",
        "insert into Quotes (episode, character, quote) values (1, 5, '…どうするの？　スクールアイドル');",
        "insert into Quotes (episode, character, quote) values (1, 9, '部長のせつ菜ちゃんに話そうとしたんだけど　連絡つかないんだ\n少し活動を休止するだけって話だったのに…\n廃部だなんて…');",
        "insert into Quotes (episode, character, quote) values (1, 5, 'そんな顔しないで\n力になれることあるかしら？');",
        "insert into Quotes (episode, character, quote) values (1, 3, 'ぬぬぬぬぬ…！\nかすみんはやっぱり　諦めませんよ！');",
        "insert into Quotes (episode, character, quote) values (1, 2, '限定のラクレットチーズはちみつ　食べる？');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'じゃあ　半分こね');",
        "insert into Quotes (episode, character, quote) values (1, 2, '残念だったね…\nせつ菜さん…');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'でも　学校にはいるはずだし　会おうと思えば…');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'それはいいよ　やめる理由があったんだろうし');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'やっぱり難しいのかな\n夢　追いかけるのって…');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'アイドルやるって　そういうことでしょ？\n自分の夢は　まだ　ないけどさ…\n夢を追いかけてる人を　応援できたら…\n私も　何かが始まる！\nそんな気が　したんだけどなあ');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'なんてね！');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'お台場寄って帰ろっか');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'あのシャツどうしよっかなあ');",
        "insert into Quotes (episode, character, quote) values (1, 2, '明日　また見てみよ？');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'あっ　そういえば　明日の数学さ…');",
        "insert into Quotes (episode, character, quote) values (1, 2, '二人で…\n二人で始めようよ　侑ちゃん！');",
        "insert into Quotes (episode, character, quote) values (1, 2, '私も見てたの　動画　スクールアイドルの…\nせつ菜さんのだけじゃなくて　たくさん…\n本当にすごいと思ったよ！');",
        "insert into Quotes (episode, character, quote) values (1, 2, '自分の気持ちをあんなにまっすぐ伝えられるなんて　スクールアイドルって　本当にすごい！\n私もあんなふうにできたら　なんてすてきだろうって！');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'ごめんね　最初に言えなくて…\n本当は私もせつ菜さんに会ってみたかった\nけど　会っちゃったら　自分の気持ちが止まらなくなりそうで怖かったの');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'それでも…　動き始めたなら　止めちゃいけない　我慢しちゃいけない');",
        "insert into Quotes (episode, character, quote) values (1, 2, '私　好きなの！');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'ピンクとか　かわいい服だって…　今でも大好きだし　着てみたいって思う！');",
        "insert into Quotes (episode, character, quote) values (1, 2, '自分に素直になりたい\nだから…　見ててほしい');",
        "insert into Quotes (episode, character, quote) values (1, 2, '私は！\nスクールアイドル　やってみたい！');",
        "insert into Quotes (episode, character, quote) values (1, 2, 'スー…　ハー…');",
        "insert into Quotes (episode, character, quote) values (1, 2, '今はまだ…\n勇気も自信も…　全然だから\nこれが　精いっぱい\n私の夢を…　一緒にみてくれる？');",
        "insert into Quotes (episode, character, quote) values (1, 1, 'もちろん！\nいつだって私は　歩夢の隣にいるよ');",
        "insert into Quotes (episode, character, quote) values (1, 3, 'ぐぬぬ〜！\nおのれ…　生徒会！');",
    ]
}

for table in sqls:
    for sql in sqls[table]:
        conn.execute(sql)
        
conn.commit()

cur.close()
conn.close()